-- vim.keymap.set("n", "<C-h>", "<C-w>H", { desc = "Move window to the left" })
-- vim.keymap.set("n", "<C-l>", "<C-w>L", { desc = "Move window to the right" })
-- vim.keymap.set("n", "<C-j>", "<C-w>J", { desc = "Move window to the lower" })
-- vim.keymap.set("n", "<C-k>", "<C-w>K", { desc = "Move window to the upper" })
