splash = false
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/1-dark-waters.jpg
    fit_mode = contain
  }

wallpaper {
    monitor = DP-1
    path = ~/.config/backgrounds/2-night-hawks.png
    fit_mode = cover
  }

wallpaper {
    monitor = DP-2
    path = ~/.config/backgrounds/01-nature-of-fear.jpg
    fit_mode = cover
  }
